# Generated by Django 4.0.4 on 2022-05-12 15:55

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aperture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minApertureType', models.CharField(max_length=100)),
                ('maxApertureType', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(100000000)])),
                ('continuousShootingRate', models.IntegerField()),
                ('resolution', models.FloatField()),
                ('cardSlots', models.IntegerField()),
                ('jack', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FocalLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromLength', models.IntegerField()),
                ('toLength', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productFrontImage', models.ImageField(upload_to='CameraShop/static/CameraShop/img/save')),
                ('productBackImage', models.ImageField(upload_to='CameraShop/static/CameraShop/img/save')),
                ('photo1', models.ImageField(upload_to='CameraShop/static/CameraShop/img/save')),
                ('photo2', models.ImageField(upload_to='CameraShop/static/CameraShop/img/save')),
            ],
        ),
        migrations.CreateModel(
            name='ISOSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromSpeed', models.IntegerField()),
                ('toSpeed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('aperture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CameraShop.aperture')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CameraShop.color')),
                ('focalLength', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CameraShop.focallength')),
            ],
        ),
        migrations.CreateModel(
            name='LensFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lensTypeFormat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LensMount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShutterSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromSpeed', models.IntegerField()),
                ('toSpeed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dateOfBirth', models.DateField()),
                ('phoneNumber', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LensBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMethods', models.CharField(choices=[('Ship Cod', 'Thanh toán khi nhận hàng'), ('Banking', 'Thanh toán qua thẻ tín dụng'), ('Amortization', 'Trả góp')], max_length=100)),
                ('releaseTime', models.DateTimeField()),
                ('totalMoney', models.FloatField()),
                ('lens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CameraShop.lens')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CameraShop.user')),
            ],
        ),
        migrations.AddField(
            model_name='lens',
            name='lensFormat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CameraShop.lensformat'),
        ),
        migrations.AddField(
            model_name='lens',
            name='lensMount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CameraShop.lensmount'),
        ),
        migrations.CreateModel(
            name='ColorList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ManyToManyField(to='CameraShop.color', verbose_name='list of color')),
            ],
        ),
        migrations.CreateModel(
            name='CameraBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMethods', models.CharField(choices=[('Ship Cod', 'Thanh toán khi nhận hàng'), ('Banking', 'Thanh toán qua thẻ tín dụng'), ('Amortization', 'Trả góp')], max_length=100)),
                ('releaseTime', models.DateTimeField()),
                ('totalMoney', models.FloatField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CameraShop.camera')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CameraShop.color')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CameraShop.user')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='colors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CameraShop.colorlist'),
        ),
        migrations.AddField(
            model_name='camera',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CameraShop.company'),
        ),
        migrations.AddField(
            model_name='camera',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CameraShop.image'),
        ),
        migrations.AddField(
            model_name='camera',
            name='isoSpeed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CameraShop.isospeed'),
        ),
        migrations.AddField(
            model_name='camera',
            name='lensMount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CameraShop.lensmount'),
        ),
        migrations.AddField(
            model_name='camera',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CameraShop.sensor'),
        ),
        migrations.AddField(
            model_name='camera',
            name='shutterSpeed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CameraShop.shutterspeed'),
        ),
    ]
