# Generated by Django 4.0.4 on 2022-06-04 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CameraShop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focallength',
            name='fromLength',
        ),
        migrations.RemoveField(
            model_name='focallength',
            name='toLength',
        ),
        migrations.AddField(
            model_name='focallength',
            name='focalLength',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lens',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CameraShop.image'),
        ),
        migrations.RemoveField(
            model_name='camera',
            name='colors',
        ),
        migrations.AddField(
            model_name='camera',
            name='colors',
            field=models.ManyToManyField(to='CameraShop.color', verbose_name='list of color'),
        ),
        migrations.DeleteModel(
            name='ColorList',
        ),
    ]
