# Generated by Django 4.0.4 on 2022-06-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CameraShop', '0002_remove_focallength_fromlength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='quantityInStock',
            field=models.IntegerField(null=True),
        ),
    ]
