# Generated by Django 4.0.4 on 2022-06-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CameraShop', '0004_alter_camera_quantityinstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='quantityInStock',
            field=models.IntegerField(null=True),
        ),
    ]
