# Generated by Django 4.0.4 on 2022-06-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CameraShop', '0005_alter_camera_quantityinstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='importDate',
            field=models.DateField(null=True),
        ),
    ]
