# Generated by Django 4.0.4 on 2022-06-10 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CameraShop', '0011_camera_isdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='lens',
            name='importDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='lens',
            name='isDiscount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lens',
            name='price',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(100000000)]),
        ),
        migrations.AddField(
            model_name='lens',
            name='quantityInStock',
            field=models.IntegerField(null=True),
        ),
    ]
