# Generated by Django 4.0.4 on 2022-06-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CameraShop', '0013_lens_description_alter_camera_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='Male', max_length=6, null=True),
        ),
    ]
