# Generated by Django 4.0.4 on 2022-06-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CameraShop', '0014_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerabill',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lensbill',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='camerabill',
            name='paymentMethods',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('Banking', 'Banking')], max_length=100),
        ),
        migrations.AlterField(
            model_name='lensbill',
            name='paymentMethods',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('Banking', 'Banking')], max_length=100),
        ),
    ]
