# Generated by Django 4.0.4 on 2022-06-19 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CameraShop', '0018_alter_order_cameras_alter_order_lens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lens',
            name='color',
        ),
        migrations.AddField(
            model_name='lens',
            name='colors',
            field=models.ManyToManyField(to='CameraShop.color', verbose_name='list of color'),
        ),
        migrations.AddField(
            model_name='lensbill',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CameraShop.color'),
        ),
    ]
