# Generated by Django 4.0.4 on 2022-06-19 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CameraShop', '0019_remove_lens_color_lens_colors_lensbill_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMethods', models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('Debit or Credit Card', 'Debit or Credit Card'), ('PayPal', 'PayPal')], max_length=100)),
                ('releaseTime', models.DateTimeField()),
                ('totalMoney', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LenBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CameraShop.color')),
                ('lens', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CameraShop.lens')),
            ],
        ),
        migrations.RemoveField(
            model_name='camerabill',
            name='paymentMethods',
        ),
        migrations.RemoveField(
            model_name='camerabill',
            name='releaseTime',
        ),
        migrations.RemoveField(
            model_name='camerabill',
            name='totalMoney',
        ),
        migrations.RemoveField(
            model_name='camerabill',
            name='user',
        ),
        migrations.DeleteModel(
            name='LensBill',
        ),
        migrations.AddField(
            model_name='bill',
            name='cameras',
            field=models.ManyToManyField(to='CameraShop.camerabill', verbose_name='list of camera bill'),
        ),
        migrations.AddField(
            model_name='bill',
            name='lens',
            field=models.ManyToManyField(to='CameraShop.lenbill', verbose_name='list of len bill'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CameraShop.user'),
        ),
    ]
