# Generated by Django 4.0.4 on 2022-06-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CameraShop', '0020_bill_lenbill_remove_camerabill_paymentmethods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='address',
            field=models.CharField(max_length=1500, null=True),
        ),
    ]
