# Generated by Django 4.0.4 on 2022-06-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CameraShop', '0024_alter_bill_totalmoney'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='totalMoneyNoDiscount',
            field=models.FloatField(null=True),
        ),
    ]
