# Generated by Django 4.0.4 on 2022-06-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CameraShop', '0025_bill_totalmoneynodiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='isAccept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='isCancel',
            field=models.BooleanField(default=False),
        ),
    ]
